/* Autogenerated header file. Please do not edit. */

/* Input structure */
static const char *invarNameList[] = {
        "cldtaui_toterror",
        "optical_depth_instantaneous",
        "bar_pres",
        "height",
        "temp",
        "be_lwp",
        "CloudBaseBestEstimate",
        "CloudLayerBottomHeightMplZwang",
        "CloudLayerTopHeightMplZwang",
        "first_cbh",
        "second_cbh",
        "third_cbh",
        NULL
};

#ifndef _INPUT_FIELDS
#define _INPUT_FIELDS

/* Input Offsets */
#define CLDTAUI_TOTERROR 0
#define OPTICAL_DEPTH_INSTANTANEOUS 1
#define BAR_PRES 2
#define HEIGHT 3
#define TEMP 4
#define BE_LWP 5
#define CLOUDBASEBESTESTIMATE 6
#define CLOUDLAYERBOTTOMHEIGHTMPLZWANG 7
#define CLOUDLAYERTOPHEIGHTMPLZWANG 8
#define FIRST_CBH 9
#define SECOND_CBH 10
#define THIRD_CBH 11

#endif /* _INPUT_FIELDS */
