/* Autogenerated header file. Please do not edit. */

/* Input structure */
static const char *transvarNameList_mfrsr_time_select_5[] = {
        "third_cbh",
        "second_cbh",
        "first_cbh",
        NULL
};
static const char *transvarNameList_mfrsr_time_mfrsrclod_vars[] = {
        "optical_depth_instantaneous",
        "cldtaui_toterror",
        NULL
};
static const char *transvarNameList_mfrsr_time_select_4[] = {
        "CloudLayerBottomHeightMplZwang",
        "CloudBaseBestEstimate",
        "CloudLayerTopHeightMplZwang",
        NULL
};
static const char *transvarNameList_mfrsr_time_select_3[] = {
        "be_lwp",
        NULL
};
static const char *transvarNameList_mfrsr_time_select_2[] = {
        "bar_pres",
        "temp",
        NULL
};

static const char *transvarNameList_select_5[] = {
        NULL
};
static const char *transvarNameList_mfrsrclod_vars[] = {
        NULL
};
static const char *transvarNameList_select_4[] = {
        NULL
};
static const char *transvarNameList_select_3[] = {
        NULL
};
static const char *transvarNameList_select_2[] = {
        "height",
        NULL
};


#ifndef _TRANS_FIELDS
#define _TRANS_FIELDS

/* Input Offsets */
#define MFRSR_TIME_SELECT_5_THIRD_CBH 0
#define MFRSR_TIME_SELECT_5_SECOND_CBH 1
#define MFRSR_TIME_SELECT_5_FIRST_CBH 2
#define MFRSR_TIME_MFRSRCLOD_VARS_OPTICAL_DEPTH_INSTANTANEOUS 0
#define MFRSR_TIME_MFRSRCLOD_VARS_CLDTAUI_TOTERROR 1
#define MFRSR_TIME_SELECT_4_CLOUDLAYERBOTTOMHEIGHTMPLZWANG 0
#define MFRSR_TIME_SELECT_4_CLOUDBASEBESTESTIMATE 1
#define MFRSR_TIME_SELECT_4_CLOUDLAYERTOPHEIGHTMPLZWANG 2
#define MFRSR_TIME_SELECT_3_BE_LWP 0
#define MFRSR_TIME_SELECT_2_BAR_PRES 0
#define MFRSR_TIME_SELECT_2_TEMP 1
#define SELECT_2_HEIGHT 0

#endif /* _TRANS_FIELDS */
