/* Autogenerated header file. Please do not edit. */

/* Output structures */
static const char *outvarNameList_ndropmfrsr_c1[] = {
        "base_time",
        "alt",
        "lon",
        "lat",
        "saturated_water_vapor_pressure",
        "lwp_adiabatic",
        "drop_number_conc_adiabatic",
        "condensation_rate",
        "drop_number_conc_toterror",
        "drop_number_conc",
        "beta",
        "source_cloud_base",
        "cloud_base_pressure",
        "cloud_base_temperature",
        "cloud_base_type",
        "cloud_thickness",
        "cloud_top_height",
        "cloud_base_height",
        "lwp_meas",
        "temp",
        "bar_pres",
        "optical_depth_instantaneous",
        "height",
        "time",
        "time_offset",
        NULL
};

#ifndef _OUTPUT_FIELDS
#define _OUTPUT_FIELDS

/* Output offsets */
#define NDROPMFRSR_C1_BASE_TIME 0
#define NDROPMFRSR_C1_ALT 1
#define NDROPMFRSR_C1_LON 2
#define NDROPMFRSR_C1_LAT 3
#define NDROPMFRSR_C1_SATURATED_WATER_VAPOR_PRESSURE 4
#define NDROPMFRSR_C1_LWP_ADIABATIC 5
#define NDROPMFRSR_C1_DROP_NUMBER_CONC_ADIABATIC 6
#define NDROPMFRSR_C1_CONDENSATION_RATE 7
#define NDROPMFRSR_C1_DROP_NUMBER_CONC_TOTERROR 8
#define NDROPMFRSR_C1_DROP_NUMBER_CONC 9
#define NDROPMFRSR_C1_BETA 10
#define NDROPMFRSR_C1_SOURCE_CLOUD_BASE 11
#define NDROPMFRSR_C1_CLOUD_BASE_PRESSURE 12
#define NDROPMFRSR_C1_CLOUD_BASE_TEMPERATURE 13
#define NDROPMFRSR_C1_CLOUD_BASE_TYPE 14
#define NDROPMFRSR_C1_CLOUD_THICKNESS 15
#define NDROPMFRSR_C1_CLOUD_TOP_HEIGHT 16
#define NDROPMFRSR_C1_CLOUD_BASE_HEIGHT 17
#define NDROPMFRSR_C1_LWP_MEAS 18
#define NDROPMFRSR_C1_TEMP 19
#define NDROPMFRSR_C1_BAR_PRES 20
#define NDROPMFRSR_C1_OPTICAL_DEPTH_INSTANTANEOUS 21
#define NDROPMFRSR_C1_HEIGHT 22
#define NDROPMFRSR_C1_TIME 23
#define NDROPMFRSR_C1_TIME_OFFSET 24

#endif /* _OUTPUT_FIELDS */
